/**
 * The typography genome: the families of Latin type as a tree, dated to the
 * first exemplar of each. `font` is a Google Fonts family that stands in for
 * the style on screen (the originals are not on Google Fonts), named in the
 * panel so the stand-in is honest.
 */
import type { TreeNode, TreeLane } from "../../../src/components/charts/LineageTree";

export type TypeNode = TreeNode & { by: string; what: string; why: string; font: string; standIn?: string; sample?: string };

export const LANES: TreeLane[] = [
  { id: "black", label: "Blackletter" },
  { id: "serif", label: "Serif" },
  { id: "sans", label: "Sans serif" },
  { id: "mono", label: "Monospace and display" },
  { id: "tech", label: "Technology" },
];

export const NODES: TypeNode[] = [
  { id: "textura", name: "Textura", year: 1455, lane: "black", parents: [], by: "Gutenberg, the 42-line Bible", what: "The scribes' formal book hand cut in metal: narrow, vertical, every stroke a lattice.", why: "The first typeface was an imitation of handwriting so exact that early buyers could not tell the difference.", font: "UnifrakturMaguntia", standIn: "UnifrakturMaguntia (a Fraktur, the nearest on Google Fonts)" },
  { id: "fraktur", name: "Fraktur", year: 1513, lane: "black", parents: ["textura"], by: "Commissioned by Maximilian I", what: "Blackletter with broken curves, lighter than Textura.", why: "The everyday German letter for four centuries, until it was abandoned in 1941.", font: "UnifrakturMaguntia" },
  { id: "humanist", name: "Humanist (Venetian)", year: 1470, lane: "serif", parents: [], influence: ["textura"], by: "Nicolas Jenson, Venice", what: "Roman type modelled on the humanist minuscule scribes wrote in Italy: low contrast, a slanted stress, a sloping bar on the e.", why: "The roman alphabet as we still set it. Everything in the serif lane descends from this.", font: "Cormorant Garamond", standIn: "Cormorant Garamond (Garalde), the closest live cut", sample: "The quick brown fox" },
  { id: "garalde", name: "Garalde (Old-style)", year: 1495, lane: "serif", parents: ["humanist"], by: "Francesco Griffo for Aldus Manutius; Garamond by 1530", what: "More contrast, a horizontal bar on the e, finer serifs. Garamond, Bembo and Caslon are all Garaldes.", why: "Five hundred years of book typography. Still the default for long reading.", font: "EB Garamond", standIn: "EB Garamond" },
  { id: "italic", name: "Italic", year: 1501, lane: "serif", parents: ["humanist"], by: "Griffo for Aldus", what: "A sloped, condensed letter modelled on chancery script, first used on its own to fit more words on a pocket page.", why: "Later paired with roman as its companion; emphasis has looked like this ever since.", font: "EB Garamond", sample: "Hamburgefonstiv" },
  { id: "transitional", name: "Transitional", year: 1757, lane: "serif", parents: ["garalde"], by: "John Baskerville; Romain du Roi before it (1692)", what: "Higher contrast, vertical stress, sharper serifs, printed on smoother paper with blacker ink.", why: "Between old-style and modern, hence the name. Times New Roman is a transitional.", font: "Libre Baskerville", standIn: "Libre Baskerville" },
  { id: "didone", name: "Didone (Modern)", year: 1784, lane: "serif", parents: ["transitional"], by: "Firmin Didot; Giambattista Bodoni by 1790", what: "Extreme contrast, hairline serifs, fully vertical stress: a letter drawn with a pointed pen and a ruler.", why: "Fashion's typeface, from Vogue to every perfume box. Beautiful at display sizes, brittle in text.", font: "Bodoni Moda", standIn: "Bodoni Moda" },
  { id: "fatface", name: "Fat face", year: 1810, lane: "mono", parents: ["didone"], by: "Robert Thorne", what: "A Didone with the thick strokes made grotesquely thicker for posters and lottery bills.", why: "The first type made to shout. Advertising begins here.", font: "Abril Fatface", standIn: "Abril Fatface" },
  { id: "slab", name: "Slab serif (Egyptian)", year: 1815, lane: "serif", parents: ["didone"], influence: ["fatface"], by: "Vincent Figgins", what: "Serifs as heavy as the strokes, no contrast, built for the poster and the sign.", why: "Loud, legible, industrial. Clarendon (1845) is the refined version; Rockwell the geometric one.", font: "Zilla Slab", standIn: "Zilla Slab" },
  { id: "clarendon", name: "Clarendon", year: 1845, lane: "serif", parents: ["slab"], by: "Robert Besley, Fann Street Foundry", what: "A bracketed slab serif with real contrast, the first typeface registered under the Designs Act.", why: "The Victorian workhorse: newspapers, railway posters, wanted signs, and every Western ever filmed.", font: "Arvo", standIn: "Arvo (a Clarendon-flavoured slab)" },
  { id: "grotesque", name: "Grotesque", year: 1816, lane: "sans", parents: [], influence: ["slab"], by: "William Caslon IV, two-line English Egyptian", what: "The first sans serif in metal: capitals only, monoline, a curiosity.", why: "Named grotesque because it looked wrong. Akzidenz-Grotesk (1898) made it a working family.", font: "Archivo", standIn: "Archivo (a modern grotesque)" },
  { id: "akzidenz", name: "Akzidenz-Grotesk", year: 1898, lane: "sans", parents: ["grotesque"], by: "H. Berthold AG", what: "A complete grotesque family for jobbing work: sizes, weights, widths.", why: "The typeface Swiss modernism chose, and the parent of Helvetica.", font: "Work Sans", standIn: "Work Sans (a grotesque)" },
  { id: "johnston", name: "Johnston", year: 1916, lane: "sans", parents: ["grotesque"], influence: ["humanist"], by: "Edward Johnston for the London Underground", what: "A sans with humanist proportions: the capitals from Roman inscriptions, the lower case from the humanist hand, a diamond dot on the i.", why: "The first humanist sans, and the typeface of London. Gill Sans (1928) is its pupil.", font: "Hammersmith One", standIn: "Hammersmith One (a Johnston-based face)" },
  { id: "gill", name: "Gill Sans", year: 1928, lane: "sans", parents: ["johnston"], by: "Eric Gill, Monotype", what: "Johnston made commercial: a full family with the humanist lower case and an idiosyncratic italic.", why: "Britain's corporate sans for most of a century: the BBC, Penguin, British Railways.", font: "Cabin", standIn: "Cabin (humanist sans)" },
  { id: "futura", name: "Futura", year: 1927, lane: "sans", parents: ["grotesque"], by: "Paul Renner, Bauer", what: "Geometry as letters: a circle for the o, a triangle for the A, strokes that only look monoline because Renner corrected them by eye.", why: "The geometric sans. Its descendants are everywhere; Jost, which sets this site, is one.", font: "Jost", standIn: "Jost (this site's face, a Futura descendant)" },
  { id: "times", name: "Times New Roman", year: 1932, lane: "serif", parents: ["transitional"], influence: ["garalde"], by: "Stanley Morison and Victor Lardent for The Times", what: "A transitional with Plantin's proportions, drawn narrow and sharp for newsprint.", why: "The most-read typeface of the twentieth century, then the default of every word processor.", font: "Tinos", standIn: "Tinos (metric-compatible with Times)" },
  { id: "courier", name: "Courier", year: 1955, lane: "mono", parents: ["slab"], by: "Howard Kettler for IBM", what: "A monospaced slab serif for the typewriter, every letter the same width.", why: "Screenplays, code listings, and the look of anything typed. Monospace begins here for most people.", font: "Courier Prime", standIn: "Courier Prime" },
  { id: "helvetica", name: "Helvetica", year: 1957, lane: "sans", parents: ["akzidenz"], by: "Max Miedinger and Eduard Hoffmann, Haas", what: "Akzidenz tidied: tighter apertures, a horizontal-terminal a, a more uniform texture.", why: "The neo-grotesque that became the air we breathe. Arial is its metric clone.", font: "Inter", standIn: "Inter (a neo-grotesque for screens)" },
  { id: "univers", name: "Univers", year: 1957, lane: "sans", parents: ["akzidenz"], by: "Adrian Frutiger, Deberny and Peignot", what: "The first typeface designed as a system: 21 variants on a numbered grid of weight and width.", why: "The idea of a type family as a coordinate space. Variable fonts are this grid made continuous.", font: "Archivo", standIn: "Archivo (grotesque, wide family)" },
  { id: "frutiger", name: "Frutiger", year: 1976, lane: "sans", parents: ["univers"], influence: ["johnston"], by: "Adrian Frutiger for Charles de Gaulle airport", what: "A humanist sans built for signage: open apertures, distinct letterforms, legible at a glance and at speed.", why: "The wayfinding face. Most airport and motorway signage descends from it.", font: "Hind", standIn: "Hind (humanist sans)" },
  { id: "postscript", name: "PostScript Type 1", year: 1984, lane: "tech", parents: [], by: "Adobe", what: "Outlines as Bézier curves in a page description language; the same font at any size, on any printer.", why: "Type stops being metal or film and becomes maths. Desktop publishing follows.", font: "Inter" },
  { id: "truetype", name: "TrueType", year: 1991, lane: "tech", parents: ["postscript"], by: "Apple, then Microsoft", what: "Quadratic outlines plus hinting instructions that tell the rasteriser how to fit strokes to a pixel grid.", why: "Fonts that stay readable on a 72 dpi screen. Every operating system shipped with it.", font: "Inter" },
  { id: "opentype", name: "OpenType", year: 1996, lane: "tech", parents: ["truetype", "postscript"], by: "Microsoft and Adobe", what: "One container for both outline flavours, Unicode, and layout features: ligatures, small caps, alternates, kerning as data.", why: "The format the web uses (as WOFF2). The typographic niceties of metal type came back as feature tags.", font: "Fraunces" },
  { id: "webfonts", name: "Web fonts (WOFF)", year: 2009, lane: "tech", parents: ["opentype"], by: "W3C; Google Fonts 2010", what: "OpenType wrapped and compressed for @font-face, served from a URL.", why: "The end of web-safe fonts. A page can look like its designer intended.", font: "Inter" },
  { id: "variable", name: "Variable fonts", year: 2016, lane: "tech", parents: ["opentype"], influence: ["univers"], by: "OpenType 1.8: Apple, Google, Microsoft, Adobe", what: "One file holding a design space with named axes (weight, width, optical size, slant) and any point between them.", why: "Univers's grid made continuous, at one file's cost. Kern exists to explore exactly this.", font: "Recursive", standIn: "Recursive (variable)" },
  { id: "inter", name: "Inter", year: 2017, lane: "sans", parents: ["helvetica"], influence: ["variable"], by: "Rasmus Andersson", what: "A neo-grotesque drawn for screens with a tall x-height, open apertures, and a variable axis.", why: "The face most of the web's interfaces are set in now. Sets the body text here.", font: "Inter" },
  { id: "fraunces", name: "Fraunces", year: 2020, lane: "serif", parents: ["didone", "garalde"], influence: ["variable"], by: "Undercase Type, for Google Fonts", what: "A soft serif with optical size, weight, softness and wonkiness axes: a family that moves between display and text.", why: "What a serif can be when it is a design space, not a set of cuts.", font: "Fraunces", standIn: "Fraunces (variable)" },
  { id: "recursive", name: "Recursive", year: 2019, lane: "mono", parents: ["courier"], influence: ["variable"], by: "Arrow Type", what: "Sans, mono and casual in one variable file: axes for monospace, casual, weight, slant and cursive.", why: "Code and prose from one font, sliding between them. The monospace lane meets the variable lane.", font: "Recursive" },
];

export const FONT_FAMILIES = Array.from(new Set(NODES.map((n) => n.font)));
