/** Every chart on labs.sammii.dev/charts, in series order. The index page and the Labs index read this. */
export type Chart = { n: string; slug: string; title: string; blurb: string; stack: string; series: string };

export const CHARTS: Chart[] = [
  { n: "01", slug: "colour-spaces", title: "The family tree of colour spaces", series: "Colour and perception", stack: "SVG, React, CSS Color 4", blurb: "25 colour spaces from Munsell and CIE XYZ to OKLCH and CSS Color 4 on a timeline in six lanes, the derivations drawn in, live ramps in each space, and the poster to download." },
  { n: "02", slug: "why-hsl-lies", title: "Why HSL lies", series: "Colour and perception", stack: "First-principles colour maths", blurb: "Twenty-four hues at one nominal lightness in HSL, CIELCH and OKLCH, with the measured luminance under every swatch. The skyline versus the flat line." },
  { n: "04", slug: "typography", title: "The typography genome", series: "Typography", stack: "Lineage tree, live specimens", blurb: "Latin type as a family tree from Textura to variable fonts, five lanes, every node shown in a live stand-in font. Serif is one unbroken line from Jenson." },
  { n: "06", slug: "gamuts", title: "The gamuts", series: "Colour and perception", stack: "CIE 1931 diagram, per-pixel canvas", blurb: "Every colour you can see as the CIE horseshoe, with sRGB, Display P3, Adobe RGB and Rec. 2020 as triangles, and a check of what your own screen can show." },
  { n: "10", slug: "named-colours", title: "Every named CSS colour, in OKLCH", series: "Colour and perception", stack: "148 names, resolved by your browser", blurb: "The named colours placed by what they look like: OKLCH hue round the wheel, chroma outward, lightness as dot size. darkgray is lighter than gray, and the wheel shows why the set is lopsided." },
  { n: "11", slug: "url", title: "How a URL becomes a page", series: "The browser and the machine", stack: "Waterfall from round trips, six knobs", blurb: "DNS, the handshakes, the first byte, the HTML, the CSS, the JavaScript and the paint as one waterfall computed from the round-trip time you pick. On a slow link the waiting dwarfs the work." },
  { n: "07", slug: "repaint", title: "What a CSS property costs", series: "The browser and the machine", stack: "Pipeline map, 55 properties", blurb: "Every common CSS property sorted by what changing it forces: layout, paint or composite. Pick one and the pipeline lights up. Two properties live in the cheap column." },
  { n: "08", slug: "event-loop", title: "The event loop, step by step", series: "The browser and the machine", stack: "Stepper, a model of the loop", blurb: "Three real snippets run through the call stack, the microtask queue, the task queue, rAF and the render step, one step at a time. Why 1, 4, 3, 2." },
  { n: "09", slug: "big-o", title: "Big O, to scale", series: "The browser and the machine", stack: "Growth curves, log and linear", blurb: "Eight complexity classes on one chart for the n you choose, and the time each takes at a billion operations a second. The log axis is the point." },
  { n: "05", slug: "keypress", title: "How a keypress becomes a pixel", series: "The browser and the machine", stack: "Latency flow, four knobs", blurb: "Twelve hops between a finger and the glass, drawn to their share of the time. The code you write is two of them; the display is three." },
  { n: "03", slug: "communication", title: "Six centuries of communication and type", series: "Typography", stack: "Scroll timeline, 65 entries", blurb: "Gutenberg to ChatGPT on one spine, inventions on the left and typefaces on the right, so the two histories read against each other." },
];

export const chartHref = (slug: string) => `https://labs.sammii.dev/charts/${slug}/`;
