/** Every chart on labs.sammii.dev/charts, in series order. The index page and the Labs index read this. */
export type Chart = { n: string; slug: string; title: string; blurb: string; stack: string; series: string };

export const CHARTS: Chart[] = [
  { n: "01", slug: "colour-spaces", title: "The family tree of colour spaces", series: "Colour and perception", stack: "SVG, React, CSS Color 4", blurb: "25 colour spaces from Munsell and CIE XYZ to OKLCH and CSS Color 4 on a timeline in six lanes, the derivations drawn in, live ramps in each space, and the poster to download." },
  { n: "02", slug: "why-hsl-lies", title: "Why HSL lies", series: "Colour and perception", stack: "First-principles colour maths", blurb: "Twenty-four hues at one nominal lightness in HSL, CIELCH and OKLCH, with the measured luminance under every swatch. The skyline versus the flat line." },
  { n: "04", slug: "typography", title: "The typography genome", series: "Typography", stack: "Lineage tree, live specimens", blurb: "Latin type as a family tree from Textura to variable fonts, five lanes, every node shown in a live stand-in font. Serif is one unbroken line from Jenson." },
  { n: "06", slug: "gamuts", title: "The gamuts", series: "Colour and perception", stack: "CIE 1931 diagram, per-pixel canvas", blurb: "Every colour you can see as the CIE horseshoe, with sRGB, Display P3, Adobe RGB and Rec. 2020 as triangles, and a check of what your own screen can show." },
  { n: "10", slug: "named-colours", title: "Every named CSS colour, in OKLCH", series: "Colour and perception", stack: "148 names, resolved by your browser", blurb: "The named colours placed by what they look like: OKLCH hue round the wheel, chroma outward, lightness as dot size. darkgray is lighter than gray, and the wheel shows why the set is lopsided." },
  { n: "14", slug: "contrast", title: "Contrast, two ways that disagree", series: "Colour and perception", stack: "WCAG 2 and APCA, first principles", blurb: "The same text and background scored by WCAG 2 and by APCA next to the rendered text, and the full grey ramp on white and on black to show where they part company. Orange on white fails one and is a fine heading in the other." },
  { n: "11", slug: "url", title: "How a URL becomes a page", series: "The browser and the machine", stack: "Waterfall from round trips, six knobs", blurb: "DNS, the handshakes, the first byte, the HTML, the CSS, the JavaScript and the paint as one waterfall computed from the round-trip time you pick. On a slow link the waiting dwarfs the work." },
  { n: "07", slug: "repaint", title: "What a CSS property costs", series: "The browser and the machine", stack: "Pipeline map, 55 properties", blurb: "Every common CSS property sorted by what changing it forces: layout, paint or composite. Pick one and the pipeline lights up. Two properties live in the cheap column." },
  { n: "08", slug: "event-loop", title: "The event loop, for interfaces", series: "The browser and the machine", stack: "Live demos plus a stepper", blurb: "Why the loading label never shows, why the CSS animation survives a busy page and the JavaScript one freezes, measured with real work. Then the rules underneath, stepped through: 1, 4, 3, 2." },
  { n: "09", slug: "big-o", title: "Big O, in the keystroke", series: "The browser and the machine", stack: "Live measured demo plus curves", blurb: "A filtered list that stops keeping up with your typing, measured per keystroke against the 16 ms and 100 ms budgets, and the one line behind it. Then eight classes to scale, log or linear, with the time each takes at a billion operations a second." },
  { n: "12", slug: "springs", title: "Easing versus springs", series: "Motion and interaction", stack: "Live physics, recorded from the screen", blurb: "A CSS transition and a spring moving the same card, both sampled from the screen every frame. Interrupt them mid-flight: the spring keeps its velocity, the transition starts a fresh curve. Stiffness, damping, mass, and the settle time a spring has instead of a duration." },
  { n: "13", slug: "stacking", title: "Why z-index: 9999 does nothing", series: "The browser and the machine", stack: "Live DOM, computed paint order", blurb: "A real dropdown on a real card. Toggle transform, opacity, filter or will-change on the card and the menu vanishes under the next section; the panel shows the stacking-context tree the browser built and the order it painted. Two fixes, one of them the start of the next war." },
  { n: "15", slug: "specificity", title: "Specificity, three columns", series: "The browser and the machine", stack: "Selectors Level 4 parser, live ranking", blurb: "Type any selector and see its specificity as three bars, with :is, :where, :not, :has and nth-child-of handled properly. The rules on one button ranked, and the seven cascade steps that get a say before specificity does." },
  { n: "17", slug: "layout", title: "Thirty years of CSS layout, the same page each way", series: "The browser and the machine", stack: "Seven eras of real CSS, live", blurb: "One page built seven times: tables, floats, inline-block, flexbox, grid, container queries and subgrid, in the real CSS of each era and rendered by your browser. Drag the width and what each era could not do is visible, not described." },
  { n: "19", slug: "unicode", title: "The four lengths of a string", series: "The browser and the machine", stack: "Live counts, Intl.Segmenter", blurb: "Why \"family\".length lies: graphemes, code points, UTF-16 units and UTF-8 bytes counted live for anything you type, every grapheme with its code points, and what a 20-character limit written three ways does to a name, a flag and a family." },
  { n: "20", slug: "floating-point", title: "Floating point, at the pixel", series: "The browser and the machine", stack: "Measured layout, decoded doubles", blurb: "The seam between tiles at a third of the width, the border that goes fuzzy at half a pixel, the basket that says 0.30000000000000004, and the 64 bits of any number you type. Measured with getBoundingClientRect and decoded with a DataView, live." },
  { n: "21", slug: "js-cost", title: "What a byte of JavaScript costs", series: "The browser and the machine", stack: "Generated bundle, measured in-page", blurb: "A bundle of the size you choose is generated, gzipped, parsed, compiled and executed in your browser and timed, then laid next to its download on the network you pick and next to the same bytes as an image. The byte is not the cost; the thread is." },
  { n: "05", slug: "keypress", title: "How a keypress becomes a pixel", series: "The browser and the machine", stack: "Latency flow, four knobs", blurb: "Twelve hops between a finger and the glass, drawn to their share of the time. The code you write is two of them; the display is three." },
  { n: "16", slug: "seven", title: "Seven, and why the week is in that order", series: "Number and symbol", stack: "Planetary hours, stepped live", blurb: "Step the hours of the week and the seven-pointed star draws itself: 24 mod 7 = 3 is why the days go Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn. Then the sevens in columns, from Newton's spectrum to the seven spheres of my MA installation." },
  { n: "18", slug: "x-height", title: "Why 16px is not 16px", series: "Typography", stack: "22 families measured live, canvas API", blurb: "font-size is a box and every family fills it differently. Twenty-two families loaded and measured in your browser: x-height, cap height, ascender, descender and line box as fractions of the em, the size each needs to match a reference, and font-size-adjust switched on live." },
  { n: "03", slug: "communication", title: "Six centuries of communication and type", series: "Typography", stack: "Scroll timeline, 65 entries", blurb: "Gutenberg to ChatGPT on one spine, inventions on the left and typefaces on the right, so the two histories read against each other." },
];

export const chartHref = (slug: string) => `https://labs.sammii.dev/charts/${slug}/`;
